.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. genesis-qt test_genesis-qt
clean: FORCE
	$(MAKE) -C .. genesis-qt_clean test_genesis-qt_clean
check: FORCE
	$(MAKE) -C .. test_genesis-qt_check
genesis-qt genesis-qt.exe: FORCE
	 $(MAKE) -C .. genesis-qt
